# Устанавливаем базовый образ Ubuntu
FROM ubuntu:latest

# Обновляем пакеты и устанавливаем необходимые утилиты
RUN apt-get update && \
    apt-get install -y \
    openssh-server \
    sudo

# Создаем директорию для хранения ключей SSH и создаем файл конфигурации
RUN mkdir /var/run/sshd && \
    echo 'root:password' | chpasswd

# Разрешаем вход по паролю для root (не рекомендуется для продакшн-окружений)
RUN sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Открываем порт 22 для SSH
EXPOSE 22

# Запускаем SSH сервер
CMD ["/usr/sbin/sshd", "-D"]
