
FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 9999 test
RUN service ssh start
EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
